# permissions for end users to edit wavefrontoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wavefrontoperator-editor-role
rules:
- apiGroups:
  - wavefront.com
  resources:
  - wavefrontoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wavefront.com
  resources:
  - wavefrontoperators/status
  verbs:
  - get
