# permissions for end users to view wavefrontoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wavefrontoperator-viewer-role
rules:
- apiGroups:
  - wavefront.com
  resources:
  - wavefrontoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wavefront.com
  resources:
  - wavefrontoperators/status
  verbs:
  - get
