# wavefront_collector_configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: wavefront
data:
  collector.yaml: |
    clusterName: k8s-demo-cluster
    enableDiscovery: true

    sinks:
    - proxyAddress: example-wavefrontproxy.wavefront.svc.cluster.local:2878
      tags:
        version: 1.2.3

    sources:
      kubernetes_source:
        url: 'https://kubernetes.default.svc'
        kubeletPort: 10250
        kubeletHttps: true
        useServiceAccount: true
        insecure: true
        prefix: 'kubernetes.'

      internal_stats_source:
        prefix: 'kubernetes.'

      kubernetes_state_source:
        prefix: 'kubernetes.'

      telegraf_sources:
      - plugins: []

    discovery:
      enable_runtime_plugins: false
      plugins:
      - name: kube-dns-discovery
        type: prometheus
        selectors:
          labels:
            k8s-app:
            - kube-dns
        port: 10054
        path: /metrics
        scheme: http
        prefix: kube.dns.
---
# wavefront_collector_cr.yaml
apiVersion: wavefront.com/v1alpha1
kind: WavefrontCollector
metadata:
  name: wavefront-collector
  namespace: wavefront
spec:
  image: wavefronthq/wavefront-kubernetes-collector:1.2.3
  daemon: true
  configName: collector-config

  env:
  - name: HOST_PROC
    value: /host/proc
  - name: POD_NODE_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: spec.nodeName
  - name: POD_NAMESPACE_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace

  tolerations:
  - effect: NoSchedule
    key: node.alpha.kubernetes.io/role
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
